# Generated by Django 3.1.5 on 2021-04-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='presentation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
