# Generated by Django 3.1.5 on 2021-05-04 17:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_auto_20210503_1631'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('chatroom', 'user')},
        ),
    ]
