# Generated by Django 3.1.2 on 2021-01-12 19:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favs',
            field=models.ManyToManyField(related_name='all_favs', through='blog.Favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
