# Generated by Django 3.1.5 on 2021-05-03 20:53

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_favs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='no-image.png', upload_to=blog.models.user_directory_path),
        ),
    ]
